server {
    listen 80;

    # الجزء الخاص بالـ Frontend
    # Nginx هيدور على ملف الـ index.html اللي رفعناه في الفولدر ده
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # الجزء الخاص بالـ Backend (الـ Reverse Proxy)
    # أي طلب بيبدأ بـ /api/ هيتوجه فوراً لحاوية الـ Backend
    location /api/ {
        proxy_pass http://backend:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
